name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set package version
      id: set_version
      run: |
        TAG=$(git describe --tags --abbrev=0)
        VERSION=${TAG#v} # Remove 'v' prefix if present

        echo "::set-output name=package_version::${VERSION}"

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Resulty to NuGet
      run: |
        rm -rf nuget/
        dotnet pack --no-build src/Resulty/Resulty.csproj --configuration Release -p:PackageVersion=${{ steps.set_version.outputs.package_version }} --output nuget
        dotnet nuget push nuget/*.nupkg --skip-duplicate --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}